spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/football_bot_db
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

domain:

  bot:
    name: override
    token: override

  teams:
    - name: "csi"
      chat_id: -1001142763396
      day: Среда_21:00
      check-in-before-hours: 56
      send-team-report-before-hours: 1
      ignore-addition: false
      ignore-interrogation: false

    - name: "ros_telecom"
      chat_id: -1003541602308
      day: Понедельник_21:00
      check-in-before-hours: 32
      send-team-report-before-hours: 1
      ignore-addition: false
      ignore-interrogation: false
